# This file is auto-generated by test.py. Do not edit manually.

from pydantic import BaseModel
from typing import Optional, Any
from datetime import datetime, date

class ApplianceCreate(BaseModel):
    project_id: Optional[int] = None
    appliance_name: Optional[str] = None
    type: Optional[str] = None
    qty: Optional[int] = None
    use_hours_night: Optional[float] = None
    wattage: Optional[float] = None
    energy_consumption: Optional[float] = None

class ApplianceUpdate(BaseModel):
    project_id: Optional[int] = None
    appliance_name: Optional[str] = None
    type: Optional[str] = None
    qty: Optional[int] = None
    use_hours_night: Optional[float] = None
    wattage: Optional[float] = None
    energy_consumption: Optional[float] = None


class ApplicationSettingsCreate(BaseModel):
    language: Optional[str] = None
    last_saved_path: Optional[str] = None
    other_settings: Optional[Any] = None
    user_id: Optional[int] = None

class ApplicationSettingsUpdate(BaseModel):
    language: Optional[str] = None
    last_saved_path: Optional[str] = None
    other_settings: Optional[Any] = None
    user_id: Optional[int] = None


class AuthenticationCreate(BaseModel):
    user_id: Optional[int] = None
    password_hash: Optional[str] = None
    password_salt: Optional[str] = None
    current_jwt: Optional[str] = None
    jwt_issued_at: Optional[datetime] = None
    device_id: Optional[str] = None
    is_logged_in: Optional[bool] = None
    last_active: Optional[datetime] = None

class AuthenticationUpdate(BaseModel):
    user_id: Optional[int] = None
    password_hash: Optional[str] = None
    password_salt: Optional[str] = None
    current_jwt: Optional[str] = None
    jwt_issued_at: Optional[datetime] = None
    device_id: Optional[str] = None
    is_logged_in: Optional[bool] = None
    last_active: Optional[datetime] = None


class CustomerCreate(BaseModel):
    full_name: str
    date_created: Optional[datetime] = None
    phone_number: Optional[str] = None
    email: Optional[str] = None
    org_id: Optional[int] = None
    user_id: Optional[int] = None

class CustomerUpdate(BaseModel):
    full_name: Optional[str] = None
    date_created: Optional[datetime] = None
    phone_number: Optional[str] = None
    email: Optional[str] = None
    org_id: Optional[int] = None
    user_id: Optional[int] = None


class DocumentCreate(BaseModel):
    project_id: Optional[int] = None
    date_created: Optional[datetime] = None
    last_edited_date: Optional[datetime] = None
    doc_type: Optional[str] = None
    file_name: Optional[str] = None
    file_blob: Optional[Any] = None

class DocumentUpdate(BaseModel):
    project_id: Optional[int] = None
    date_created: Optional[datetime] = None
    last_edited_date: Optional[datetime] = None
    doc_type: Optional[str] = None
    file_name: Optional[str] = None
    file_blob: Optional[Any] = None


class InvoiceCreate(BaseModel):
    project_id: Optional[int] = None
    user_id: Optional[int] = None
    amount: Optional[float] = None
    status: Optional[str] = None
    issued_at: Optional[datetime] = None

class InvoiceUpdate(BaseModel):
    project_id: Optional[int] = None
    user_id: Optional[int] = None
    amount: Optional[float] = None
    status: Optional[str] = None
    issued_at: Optional[datetime] = None


class PaymentCreate(BaseModel):
    invoice_id: Optional[int] = None
    date_created: Optional[datetime] = None
    last_edited_date: Optional[datetime] = None
    amount: Optional[float] = None
    method: Optional[str] = None

class PaymentUpdate(BaseModel):
    invoice_id: Optional[int] = None
    date_created: Optional[datetime] = None
    last_edited_date: Optional[datetime] = None
    amount: Optional[float] = None
    method: Optional[str] = None


class ProjectCreate(BaseModel):
    date_created: Optional[datetime] = None
    last_edited_date: Optional[datetime] = None
    customer_id: Optional[int] = None
    status: Optional[str] = None
    system_config_id: Optional[int] = None
    user_id: Optional[int] = None
    org_id: Optional[int] = None
    project_location: Optional[str] = None

class ProjectUpdate(BaseModel):
    date_created: Optional[datetime] = None
    last_edited_date: Optional[datetime] = None
    customer_id: Optional[int] = None
    status: Optional[str] = None
    system_config_id: Optional[int] = None
    user_id: Optional[int] = None
    org_id: Optional[int] = None
    project_location: Optional[str] = None


class SubscriptionCreate(BaseModel):
    user_id: Optional[int] = None
    payment_id: Optional[int] = None
    date_created: Optional[datetime] = None
    expiration_date: Optional[datetime] = None
    grace_period_end: Optional[datetime] = None
    type: Optional[str] = None
    status: Optional[str] = None
    license_code: Optional[str] = None

class SubscriptionUpdate(BaseModel):
    user_id: Optional[int] = None
    payment_id: Optional[int] = None
    date_created: Optional[datetime] = None
    expiration_date: Optional[datetime] = None
    grace_period_end: Optional[datetime] = None
    type: Optional[str] = None
    status: Optional[str] = None
    license_code: Optional[str] = None


class SubscriptionPaymentCreate(BaseModel):
    amount: Optional[float] = None
    payment_method: Optional[str] = None
    payment_date: Optional[datetime] = None
    transaction_reference: Optional[Any] = None
    status: Optional[str] = None

class SubscriptionPaymentUpdate(BaseModel):
    amount: Optional[float] = None
    payment_method: Optional[str] = None
    payment_date: Optional[datetime] = None
    transaction_reference: Optional[Any] = None
    status: Optional[str] = None


class SyncLogCreate(BaseModel):
    sync_date: Optional[datetime] = None
    sync_type: Optional[str] = None
    data_type: Optional[str] = None
    status: Optional[str] = None
    user_id: Optional[int] = None

class SyncLogUpdate(BaseModel):
    sync_date: Optional[datetime] = None
    sync_type: Optional[str] = None
    data_type: Optional[str] = None
    status: Optional[str] = None
    user_id: Optional[int] = None


class SystemConfigurationCreate(BaseModel):
    config_items: Optional[Any] = None
    total_wattage: Optional[float] = None

class SystemConfigurationUpdate(BaseModel):
    config_items: Optional[Any] = None
    total_wattage: Optional[float] = None


class UserCreate(BaseModel):
    username: str
    registration_date: Optional[datetime] = None
    email: str
    business_name: Optional[str] = None
    account_type: Optional[str] = None
    location: Optional[str] = None
    business_logo: Optional[Any] = None
    business_email: Optional[str] = None
    status: Optional[str] = None
    org_id: Optional[int] = None
    org_name: Optional[str] = None
    branch_id: Optional[int] = None
    branch_location: Optional[str] = None
    role: Optional[str] = None

class UserUpdate(BaseModel):
    username: Optional[str] = None
    registration_date: Optional[datetime] = None
    email: Optional[str] = None
    business_name: Optional[str] = None
    account_type: Optional[str] = None
    location: Optional[str] = None
    business_logo: Optional[Any] = None
    business_email: Optional[str] = None
    status: Optional[str] = None
    org_id: Optional[int] = None
    org_name: Optional[str] = None
    branch_id: Optional[int] = None
    branch_location: Optional[str] = None
    role: Optional[str] = None


