# This file is auto-generated by test.py. Do not edit manually.

from pydantic import BaseModel
from typing import Optional
from datetime import datetime, date

class ApplianceCreate(BaseModel):
    project_id: int
    appliance_name: str
    wattage: float
    quantiy: int
    user_time_hours: float
    energy_consumption: float

class ApplianceUpdate(BaseModel):
    project_id: Optional[int] = None
    appliance_name: Optional[str] = None
    wattage: Optional[float] = None
    quantiy: Optional[int] = None
    user_time_hours: Optional[float] = None
    energy_consumption: Optional[float] = None


class ApplicationSettingCreate(BaseModel):
    organization_id: Optional[int] = None
    key_name: str
    value: Optional[str] = None
    value_type: Optional[str] = None
    updated_by_user: Optional[int] = None

class ApplicationSettingUpdate(BaseModel):
    organization_id: Optional[int] = None 
    key_name: Optional[str] = None
    value: Optional[str] = None 
    value_type: Optional[str] = None 
    updated_by_user: Optional[int] = None 


class AuthenticationCreate(BaseModel):
    user_id: int
    password_hash: str
    password_salt: Optional[str] = None
    current_jwt: Optional[str] = None
    jwt_issued_at: Optional[datetime] = None
    device_id: Optional[str] = None
    is_logged_in: Optional[bool] = None
    last_active: Optional[datetime] = None

class AuthenticationUpdate(BaseModel):
    user_id: Optional[int] = None
    password_hash: Optional[str] = None
    password_salt: Optional[str] = None 
    current_jwt: Optional[str] = None 
    jwt_issued_at: Optional[datetime] = None 
    device_id: Optional[str] = None 
    is_logged_in: Optional[bool] = None 
    last_active: Optional[datetime] = None 


class BranchCreate(BaseModel):
    organization_id: int
    branch_name: str
    branch_location: Optional[str] = None
    contact_email: Optional[str] = None
    contact_phone: Optional[str] = None

class BranchUpdate(BaseModel):
    organization_id: Optional[int] = None
    branch_name: Optional[str] = None
    branch_location: Optional[str] = None 
    contact_email: Optional[str] = None 
    contact_phone: Optional[str] = None 


class CustomerCreate(BaseModel):
    organization_id: Optional[int] = None
    branch_id: Optional[int] = None
    name: str
    contact_email: Optional[str] = None
    contact_phone: Optional[str] = None
    address: Optional[str] = None
    tax_id: Optional[str] = None
    notes: Optional[str] = None

class CustomerUpdate(BaseModel):
    organization_id: Optional[int] = None 
    branch_id: Optional[int] = None
    name: Optional[str] = None
    contact_email: Optional[str] = None
    contact_phone: Optional[str] = None
    address: Optional[str] = None
    tax_id: Optional[str] = None
    notes: Optional[str] = None


class LicenseCreate(BaseModel):
    license_code: str
    license_plan: str
    issued_for_org_id: Optional[int] = None
    issued_for_user_id: Optional[int] = None
    issued_at: datetime
    expires_at: Optional[datetime] = None
    max_seats: Optional[int] = None

class LicenseUpdate(BaseModel):
    license_code: Optional[str] = None
    license_plan: Optional[str] = None
    issued_for_org_id: Optional[int] = None
    issued_for_user_id: Optional[int] = None
    issued_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None
    max_seats: Optional[int] = None


class LicenseAuditCreate(BaseModel):
    license_code: str
    checked_at_local: datetime
    server_time: Optional[datetime] = None
    server_signature: Optional[str] = None
    verification_result: str
    notes: Optional[str] = None

class LicenseAuditUpdate(BaseModel):
    license_code: Optional[str] = None
    checked_at_local: Optional[datetime] = None
    server_time: Optional[datetime] = None
    server_signature: Optional[str] = None
    verification_result: Optional[str] = None
    notes: Optional[str] = None


class OrganizationCreate(BaseModel):
    organization_name: str
    legal_email: Optional[str] = None
    registration_date: Optional[date] = None
    status: Optional[str] = None

class OrganizationUpdate(BaseModel):
    organization_name: Optional[str] = None
    legal_email: Optional[str] = None
    registration_date: Optional[date] = None
    status: Optional[str] = None


class OrganizationUserCreate(BaseModel):
    organization_id: int
    branch_id: Optional[int] = None
    user_id: int
    role: Optional[str] = None
    is_active: Optional[bool] = None

class OrganizationUserUpdate(BaseModel):
    organization_id: Optional[int] = None
    branch_id: Optional[int] = None
    user_id: Optional[int] = None
    role: Optional[str] = None
    is_active: Optional[bool] = None


class PaymentCreate(BaseModel):
    user_id: int
    paymed_date: datetime
    payment_method: str
    amount: int
    transaction_ref: str
    verified_by: Optional[str] = None
    verification_date: Optional[date] = None
    status: Optional[str] = None

class PaymentUpdate(BaseModel):
    user_id: Optional[int] = None
    paymed_date: Optional[datetime] = None
    payment_method: Optional[str] = None
    amount: Optional[int] = None
    transaction_ref: Optional[str] = None
    verified_by: Optional[str] = None
    verification_date: Optional[date] = None
    status: Optional[str] = None


class ProjectCreate(BaseModel):
    user_id: int
    organization_id: Optional[int] = None
    branch_id: Optional[int] = None
    customer_id: Optional[int] = None
    client_name: str
    project_status: str
    total_cost: Optional[int] = None
    proposal_path: Optional[str] = None
    loads_breakdown_path: Optional[str] = None

class ProjectUpdate(BaseModel):
    user_id: Optional[int] = None
    organization_id: Optional[int] = None
    branch_id: Optional[int] = None
    customer_id: Optional[int] = None
    client_name: Optional[str] = None
    project_status: Optional[str] = None
    total_cost: Optional[int] = None
    proposal_path: Optional[str] = None
    loads_breakdown_path: Optional[str] = None


class ProjectItemCreate(BaseModel):
    project_id: int
    item_category: str
    item_name: str
    unit_price: int
    quantity: int
    total_price: int

class ProjectItemUpdate(BaseModel):
    project_id: Optional[int] = None
    item_category: Optional[str] = None
    item_name: Optional[str] = None
    unit_price: Optional[int] = None
    quantity: Optional[int] = None
    total_price: Optional[int] = None


class SolarSystemConfigCreate(BaseModel):
    project_id: int
    panel_brand: str
    panel_type: str
    panel_wattage: float
    panel_connection: str
    inverter_brand: str
    inverter_capacity: float
    battery_brand: str
    battery_type: str
    battery_connection: str
    total_system_cost: int

class SolarSystemConfigUpdate(BaseModel):
    project_id: Optional[int] = None
    panel_brand: Optional[str] = None
    panel_type: Optional[str] = None
    panel_wattage: Optional[float] = None
    panel_connection: Optional[str] = None
    inverter_brand: Optional[str] = None
    inverter_capacity: Optional[float] = None
    battery_brand: Optional[str] = None
    battery_type: Optional[str] = None
    battery_connection: Optional[str] = None
    total_system_cost: Optional[int] = None


class SubscriptionCreate(BaseModel):
    user_id: int
    license_code: str
    plan_type: Optional[str] = None
    start_date: datetime
    end_date: Optional[datetime] = None
    grace_period_end: Optional[datetime] = None
    is_active: Optional[bool] = None
    verification_status: Optional[str] = None
    issued_by: Optional[str] = None
    payment_id: Optional[int] = None

class SubscriptionUpdate(BaseModel):
    user_id: Optional[int] = None
    license_code: Optional[str] = None
    plan_type: Optional[str] = None
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    grace_period_end: Optional[datetime] = None
    is_active: Optional[bool] = None
    verification_status: Optional[str] = None
    issued_by: Optional[str] = None
    payment_id: Optional[int] = None


class SyncLogCreate(BaseModel):
    sync_date: datetime
    user_id: int
    sync_type: str
    data_type: str
    status: str
    notes: Optional[str] = None

class SyncLogUpdate(BaseModel):
    sync_date: Optional[datetime] = None
    user_id: Optional[int] = None
    sync_type: Optional[str] = None
    data_type: Optional[str] = None
    status: Optional[str] = None
    notes: Optional[str] = None


class UserCreate(BaseModel):
    username: str
    business_name: str
    email: str
    phone_number: str
    location: str
    logo_path: str
    business_email: str
    business_phone: str
    registration_date: date
    status: Optional[str] = None
    language: int

class UserUpdate(BaseModel):
    username: Optional[str] = None
    business_name: Optional[str] = None
    email: Optional[str] = None
    phone_number: Optional[str] = None
    location: Optional[str] = None
    logo_path: Optional[str] = None
    business_email: Optional[str] = None
    business_phone: Optional[str] = None
    registration_date: Optional[date] = None
    status: Optional[str] = None
    language: Optional[int] = None


