"""Initial schema

Revision ID: 08b2dece10ce
Revises: 
Create Date: 2025-12-06 16:20:07.600219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b2dece10ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organizations',
    sa.Column('organization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('legal_email', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'pending'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('business_phone', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'trial', 'grace'), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ApplicationSettings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Enum('string', 'number', 'boolean', 'json'), nullable=True),
    sa.Column('updated_by_user', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['updated_by_user'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('organization_id', 'key_name')
    )
    op.create_table('Authentication',
    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('password_salt', sa.String(length=255), nullable=True),
    sa.Column('current_jwt', sa.Text(), nullable=True),
    sa.Column('jwt_issued_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('auth_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Branches',
    sa.Column('branch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('branch_location', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('Licenses',
    sa.Column('license_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_code', sa.String(length=255), nullable=False),
    sa.Column('license_plan', sa.Enum('monthly', 'annual', 'lifetime'), nullable=False),
    sa.Column('issued_for_org_id', sa.Integer(), nullable=True),
    sa.Column('issued_for_user_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_for_org_id'], ['Organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['issued_for_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('license_id'),
    sa.UniqueConstraint('license_code')
    )
    op.create_table('Payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paymed_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('bankak', 'fawry', 'bnmb', 'ocash', 'mycashi', 'bravo', 'bede', 'other'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_ref', sa.String(length=255), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('SyncLog',
    sa.Column('sync_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.Enum('download', 'upload'), nullable=False),
    sa.Column('data_type', sa.Enum('projects', 'proposals', 'sales', 'settings'), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_table('Customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['Branches.branch_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('LicenseAudit',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_code', sa.String(length=255), nullable=False),
    sa.Column('checked_at_local', sa.DateTime(), nullable=False),
    sa.Column('server_time', sa.DateTime(), nullable=True),
    sa.Column('server_signature', sa.String(length=1024), nullable=True),
    sa.Column('verification_result', sa.Enum('ok', 'tampered', 'expired', 'unknown'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_code'], ['Licenses.license_code'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('OrganizationUsers',
    sa.Column('org_user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'user'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['Branches.branch_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('org_user_id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'branch_id', name='org_user_unique')
    )
    op.create_table('Subscriptions',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_code', sa.String(length=255), nullable=False),
    sa.Column('plan_type', sa.Enum('trial', 'monthly', 'annual', 'lifetime'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'revoked'), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_code'], ['Licenses.license_code'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['Payments.payment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('Projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('project_status', sa.Enum('under evaluation', 'under execution', 'executed', 'canceled', 'other'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('proposal_path', sa.Text(), nullable=True),
    sa.Column('loads_breakdown_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['Branches.branch_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.customer_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('Appliances',
    sa.Column('appliance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('appliance_name', sa.Text(), nullable=False),
    sa.Column('wattage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('quantiy', sa.Integer(), nullable=False),
    sa.Column('user_time_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('energy_consumption', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.project_id'], ),
    sa.PrimaryKeyConstraint('appliance_id')
    )
    op.create_table('ProjectItems',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_category', sa.Enum('panel', 'inverter', 'battery', 'accessory'), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.project_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('SolarSystemConfig',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('panel_brand', sa.String(length=255), nullable=False),
    sa.Column('panel_type', sa.String(length=255), nullable=False),
    sa.Column('panel_wattage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('panel_connection', sa.Enum('series', 'parallel', 'mixed'), nullable=False),
    sa.Column('inverter_brand', sa.String(length=255), nullable=False),
    sa.Column('inverter_capacity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('battery_brand', sa.String(length=255), nullable=False),
    sa.Column('battery_type', sa.Enum('liquid', 'dry', 'lithium', 'mixed'), nullable=False),
    sa.Column('battery_connection', sa.Enum('series', 'parallel', 'mixed'), nullable=False),
    sa.Column('total_system_cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.project_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SolarSystemConfig')
    op.drop_table('ProjectItems')
    op.drop_table('Appliances')
    op.drop_table('Projects')
    op.drop_table('Subscriptions')
    op.drop_table('OrganizationUsers')
    op.drop_table('LicenseAudit')
    op.drop_table('Customers')
    op.drop_table('SyncLog')
    op.drop_table('Payments')
    op.drop_table('Licenses')
    op.drop_table('Branches')
    op.drop_table('Authentication')
    op.drop_table('ApplicationSettings')
    op.drop_table('Users')
    op.drop_table('Organizations')
    # ### end Alembic commands ###
